name: generate-metrics

on:
  schedule:
    # Daily at 00:10 UTC
    - cron: "10 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: iiRoy
          template: classic
          base: header, repositories
          config_timezone: America/Mexico_City
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          output_action: none

      - name: Move metrics to assets
        run: |
          mkdir -p assets
          mv metrics.svg assets/metrics.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore(stats): update metrics"
          add: "assets/metrics.svg"
